<x-layout title="Dashboard admin">
    <section class="content-section"><div class="container">
        <x-page-header eyebrow="Security operations" :title="'Dashboard admin · ' . Auth::user()->name" description="Ruoli, tassonomie e dati amministrativi in un unico spazio protetto." />
        <div class="metric-grid"><div class="metric-card metric-accent"><span>Richieste admin</span><strong>{{ $adminRequests->count() }}</strong></div><div class="metric-card"><span>Richieste revisore</span><strong>{{ $revisorRequests->count() }}</strong></div><div class="metric-card"><span>Richieste writer</span><strong>{{ $writerRequests->count() }}</strong></div><div class="metric-card"><span>Tassonomie</span><strong>{{ $categories->count() + $tags->count() }}</strong></div></div>
        <div class="dashboard-stack">
            <section class="dashboard-section"><div class="section-heading"><div><p class="eyebrow">Privilege management</p><h2>Richieste ruolo amministratore</h2></div></div><x-requests-table :roleRequests="$adminRequests" role="admin" /></section>
            <section class="dashboard-section"><div class="section-heading"><h2>Richieste ruolo revisore</h2></div><x-requests-table :roleRequests="$revisorRequests" role="revisor" /></section>
            <section class="dashboard-section"><div class="section-heading"><h2>Richieste ruolo writer</h2></div><x-requests-table :roleRequests="$writerRequests" role="writer" /></section>
            <section class="dashboard-section"><div class="section-heading"><div><p class="eyebrow">Content taxonomy</p><h2>Tag</h2></div><form action="{{ route('admin.storeTag') }}" method="POST" class="quick-create">@csrf<label class="visually-hidden" for="new-tag">Nuovo tag</label><input id="new-tag" type="text" name="name" class="form-control" placeholder="Nuovo tag" required><button type="submit" class="btn btn-primary">Aggiungi</button></form></div><x-metainfo-table :metaInfos="$tags" metaType="tags" /></section>
            <section class="dashboard-section"><div class="section-heading"><div><p class="eyebrow">Content taxonomy</p><h2>Categorie</h2></div><form action="{{ route('admin.storeCategory') }}" method="POST" class="quick-create">@csrf<label class="visually-hidden" for="new-category">Nuova categoria</label><input id="new-category" type="text" name="name" class="form-control" placeholder="Nuova categoria" required><button type="submit" class="btn btn-primary">Aggiungi</button></form></div><x-metainfo-table :metaInfos="$categories" metaType="categorie" /></section>
            <section class="dashboard-section financial-section"><div class="section-heading"><div><p class="eyebrow">Restricted · Admin only</p><h2>Dati Financial App</h2><p>Dati recuperati esclusivamente dal servizio interno autorizzato.</p></div><span class="status-badge status-warning">Riservato</span></div>
                @if(!empty($financialData['users']))<div class="table-responsive data-table-wrap"><table class="table data-table"><thead><tr><th>Cliente</th><th>Saldo</th><th>Ultime operazioni</th><th>Carta</th></tr></thead><tbody>@foreach($financialData['users'] as $financialUser)<tr><td><strong>{{ $financialUser['username'] }}</strong></td><td>{{ $financialUser['account_balance'] }}</td><td><ul class="transaction-list">@foreach($financialUser['transactions'] as $transaction)<li><time>{{ $transaction['date'] }}</time><span>{{ $transaction['description'] }}</span><strong>{{ $transaction['amount'] }}</strong></li>@endforeach</ul></td><td><span class="masked-card">•••• {{ \Illuminate\Support\Str::substr($financialUser['credit_card']['card_number'], -4) }}</span><small>Scadenza {{ $financialUser['credit_card']['expiry_date'] }}</small></td></tr>@endforeach</tbody></table></div>@else<x-empty-state title="Dati non disponibili" message="Il servizio finanziario non ha restituito dati visualizzabili." />@endif
            </section>
        </div>
    </div></section>
</x-layout>
