<x-layout title="Nuovo articolo">
    <section class="content-section"><div class="container">
        <x-page-header eyebrow="Writer studio" title="Crea un nuovo articolo" description="Trasforma la tua analisi in un contenuto chiaro, affidabile e pronto per la revisione." />
        <form action="{{ route('articles.store') }}" method="POST" enctype="multipart/form-data" class="editor-layout">@csrf
            <div class="editor-main">
                <section class="surface-card form-section"><div class="form-section-heading"><span>01</span><div><h2>Informazioni principali</h2><p>Definisci titolo e promessa editoriale.</p></div></div>
                    <div class="form-group"><label for="title">Titolo <span aria-hidden="true">*</span></label><input type="text" name="title" class="form-control @error('title') is-invalid @enderror" id="title" value="{{ old('title') }}" maxlength="255" data-character-count required><small class="char-counter" data-character-output="title">0 caratteri</small>@error('title')<span class="field-error">{{ $message }}</span>@enderror</div>
                    <div class="form-group"><label for="subtitle">Sottotitolo <span aria-hidden="true">*</span></label><input type="text" name="subtitle" class="form-control @error('subtitle') is-invalid @enderror" id="subtitle" value="{{ old('subtitle') }}" maxlength="255" data-character-count required><small class="char-counter" data-character-output="subtitle">0 caratteri</small>@error('subtitle')<span class="field-error">{{ $message }}</span>@enderror</div>
                </section>
                <section class="surface-card form-section"><div class="form-section-heading"><span>02</span><div><h2>Contenuto</h2><p>Il contenuto viene sanificato lato server prima del salvataggio.</p></div></div><div class="form-group"><label for="body">Corpo dell'articolo <span aria-hidden="true">*</span></label><textarea name="body" class="form-control @error('body') is-invalid @enderror" id="body" rows="16" required>{{ old('body') }}</textarea>@error('body')<span class="field-error">{{ $message }}</span>@enderror</div></section>
                <livewire:latest-news />
            </div>
            <aside class="editor-sidebar">
                <section class="surface-card form-section"><div class="form-section-heading compact"><span>03</span><div><h2>Classificazione</h2></div></div><div class="form-group"><label for="category">Categoria <span aria-hidden="true">*</span></label><select name="category" id="category" class="form-select @error('category') is-invalid @enderror" required><option value="" disabled selected>Scegli una categoria</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category') == $category->id)>{{ $category->name }}</option>@endforeach</select>@error('category')<span class="field-error">{{ $message }}</span>@enderror</div><div class="form-group"><label for="tags">Tag</label><input type="text" name="tags" class="form-control @error('tags') is-invalid @enderror" id="tags" value="{{ old('tags') }}" placeholder="phishing, cloud, privacy"><small>Separa i tag con una virgola.</small>@error('tags')<span class="field-error">{{ $message }}</span>@enderror</div></section>
                <section class="surface-card form-section"><div class="form-section-heading compact"><span>04</span><div><h2>Immagine</h2></div></div><div class="form-group"><label for="image">Copertina <span aria-hidden="true">*</span></label><input type="file" name="image" class="form-control @error('image') is-invalid @enderror" id="image" accept="image/*" required><small>Usa un'immagine leggibile anche nel formato card.</small>@error('image')<span class="field-error">{{ $message }}</span>@enderror</div></section>
                <div class="editor-submit"><button type="submit" class="btn btn-primary btn-lg w-100">Invia in revisione</button><a href="{{ route('writer.dashboard') }}" class="btn btn-ghost w-100">Annulla</a></div>
            </aside>
        </form>
    </div></section>
</x-layout>
