<x-layout title="Modifica articolo">
    <section class="content-section"><div class="container">
        <x-page-header eyebrow="Writer studio" title="Modifica articolo" description="Aggiorna il contenuto mantenendo chiarezza, fonti e qualità editoriale." />
        <form action="{{ route('articles.update', $article) }}" method="POST" enctype="multipart/form-data" class="editor-layout">@csrf @method('PUT')
            <div class="editor-main">
                <section class="surface-card form-section"><div class="form-section-heading"><span>01</span><div><h2>Informazioni principali</h2><p>Aggiorna titolo e sottotitolo.</p></div></div><div class="form-group"><label for="title">Titolo <span aria-hidden="true">*</span></label><input type="text" name="title" class="form-control @error('title') is-invalid @enderror" id="title" value="{{ old('title', $article->title) }}" maxlength="255" data-character-count required><small class="char-counter" data-character-output="title">0 caratteri</small>@error('title')<span class="field-error">{{ $message }}</span>@enderror</div><div class="form-group"><label for="subtitle">Sottotitolo <span aria-hidden="true">*</span></label><input type="text" name="subtitle" class="form-control @error('subtitle') is-invalid @enderror" id="subtitle" value="{{ old('subtitle', $article->subtitle) }}" maxlength="255" data-character-count required><small class="char-counter" data-character-output="subtitle">0 caratteri</small>@error('subtitle')<span class="field-error">{{ $message }}</span>@enderror</div></section>
                <section class="surface-card form-section"><div class="form-section-heading"><span>02</span><div><h2>Contenuto</h2><p>La stessa sanitizzazione di sicurezza viene applicata anche alle modifiche.</p></div></div><div class="form-group"><label for="body">Corpo dell'articolo <span aria-hidden="true">*</span></label><textarea name="body" class="form-control @error('body') is-invalid @enderror" id="body" rows="16" required>{{ old('body', $article->body) }}</textarea>@error('body')<span class="field-error">{{ $message }}</span>@enderror</div></section>
            </div>
            <aside class="editor-sidebar">
                <section class="surface-card form-section"><div class="form-section-heading compact"><span>03</span><div><h2>Classificazione</h2></div></div><div class="form-group"><label for="category">Categoria</label><select name="category" id="category" class="form-select @error('category') is-invalid @enderror"><option value="" disabled>Scegli una categoria</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category', $article->category_id) == $category->id)>{{ $category->name }}</option>@endforeach</select>@error('category')<span class="field-error">{{ $message }}</span>@enderror</div><div class="form-group"><label for="tags">Tag</label><input type="text" name="tags" class="form-control @error('tags') is-invalid @enderror" id="tags" value="{{ old('tags', $article->tags->implode('name', ', ')) }}"><small>Separa i tag con una virgola.</small>@error('tags')<span class="field-error">{{ $message }}</span>@enderror</div></section>
                <section class="surface-card form-section"><div class="form-section-heading compact"><span>04</span><div><h2>Immagine</h2></div></div>@if($article->image)<img src="{{ Storage::url($article->image) }}" alt="Copertina attuale di {{ $article->title }}" class="editor-current-image">@endif<div class="form-group"><label for="image">Sostituisci copertina</label><input type="file" name="image" class="form-control @error('image') is-invalid @enderror" id="image" accept="image/*">@error('image')<span class="field-error">{{ $message }}</span>@enderror</div></section>
                <div class="editor-submit"><button type="submit" class="btn btn-primary btn-lg w-100">Salva modifiche</button><a href="{{ route('writer.dashboard') }}" class="btn btn-ghost w-100">Annulla</a></div>
            </aside>
        </form>
    </div></section>
</x-layout>
